/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ceif
 */
public class PlanningJoueur extends javax.swing.JFrame {
public static String[] InfoNom;
    String driver ="com.mysql.cj.jdbc.Driver";
            String url = "jdbc:mysql://45.90.162.130:3306/admin_cpoaG4S3";
            String username = "admin_cpoa";
            String password = "5LzPRC86Gx";
    public Connection con;
    /**
     * Creates new form PlanningJoueur
     */
    public PlanningJoueur() {
        initComponents();
        charger();
    }
    public void charger(){
        DefaultTableModel model = new DefaultTableModel(new String[]{"Joueur 1","VS","Joueur 2","Score","Terrain","Horaire","Arbitre","Ramasseur"}, 0);
        String InfJ1="";
        String InfJ2="";
           try{
            Class.forName(driver);
            con = DriverManager.getConnection(url,username,password);
            // On liste les matchs
            PreparedStatement listerMatch = con.prepareStatement("select * from lesMatch");
            ResultSet resultats = listerMatch.executeQuery();
            
            
            
            while(resultats.next()){
                // On liste infos du Joueur 1
                PreparedStatement listerInfoJoueur1 = con.prepareStatement("select nom,prenom from user,joueur where user.id= joueur.idUser and joueur.id = ?");
                listerInfoJoueur1.setString(1, resultats.getString("idJoueur1") );
                ResultSet resultatsInfoJoueur1 = listerInfoJoueur1.executeQuery();
                // On liste infos du Joueur 2
                PreparedStatement listerInfoJoueur2 = con.prepareStatement("select nom,prenom from user,joueur where user.id= joueur.idUser and joueur.id = ?");
                listerInfoJoueur2.setString(1, resultats.getString("idJoueur2") );
                ResultSet resultatsInfoJoueur2 = listerInfoJoueur2.executeQuery();
                
                
                if(resultatsInfoJoueur1.next() && resultatsInfoJoueur2.next()){
                    InfJ1 = resultatsInfoJoueur1.getString("nom") +" " + resultatsInfoJoueur1.getString("prenom");
                    InfJ2 = resultatsInfoJoueur2.getString("nom") +" " + resultatsInfoJoueur2.getString("prenom");
                    model.addRow(new Object[]{InfJ1,"   vs",InfJ2, "","","","",""});
                }
            }
            
            PlanningTable.setModel(model);
            
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PlanningTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(195, 68, 19));
        jPanel1.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel1.setText("PLANNING");

        PlanningTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Joueur 1", "VS", "Joueur 2", "Score", "Terrain", "Horaire", "Arbitre", "Ramasseur"
            }
        ));
        jScrollPane1.setViewportView(PlanningTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(438, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(430, 430, 430))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void openWindow() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlanningJoueur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlanningJoueur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlanningJoueur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlanningJoueur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlanningJoueur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PlanningTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
