/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author ceif
 */
public class PlayerHome extends javax.swing.JFrame {
    public static String[] InfoNom;
    String driver ="com.mysql.cj.jdbc.Driver";
            String url = "jdbc:mysql://45.90.162.130:3306/admin_cpoaG4S3";
            String username = "admin_cpoa";
            String password = "5LzPRC86Gx";
    public Connection con;
    /**
     * Creates new form PlayerHome
     */
    String JPrenom;
    String JNom;
    String[] sauvegarde = new String[3];
    public PlayerHome() {
        
    }
    public PlayerHome(String JId,String Nom , String Prénom){
        sauvegarde[0]=JId;
        sauvegarde[1]=Nom;
        sauvegarde[2]=Prénom;
        initComponents();
        this.JPrenom = Prénom;
        this.JNom= Nom;
        PrenomLabel.setText(this.JPrenom);
        NomLabel.setText(this.JNom);
        System.out.println(JId);
        try{
            Class.forName(driver);
            con = DriverManager.getConnection(url,username,password);
            PreparedStatement recherchePersonne = con.prepareStatement("select * from joueur where idUser=? ");
            recherchePersonne.setString(1,JId);
            ResultSet resultats = recherchePersonne.executeQuery();
            if(resultats.next()){
                AgeLabel.setText(resultats.getString("age")+" ans");
                NationnaliteLabel.setText(resultats.getString("nationnalite"));
            }
            
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ReserverButton = new javax.swing.JButton();
        PlanningButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        NomLabel = new javax.swing.JLabel();
        PrenomLabel = new javax.swing.JLabel();
        DecoButton = new javax.swing.JButton();
        AgeLabel = new javax.swing.JLabel();
        NationnaliteLabel = new javax.swing.JLabel();
        InfoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(990, 550));
        setMinimumSize(new java.awt.Dimension(990, 550));
        setPreferredSize(new java.awt.Dimension(990, 550));

        jPanel1.setBackground(new java.awt.Color(195, 68, 19));
        jPanel1.setBorder(null);
        jPanel1.setMaximumSize(new java.awt.Dimension(640, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(640, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 550));

        ReserverButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ReserverButton.setText("Reserver une scéance  d'entrainement");
        ReserverButton.setBorder(null);
        ReserverButton.setBorderPainted(false);
        ReserverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReserverButtonActionPerformed(evt);
            }
        });

        PlanningButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PlanningButton1.setText("Voir le planning");
        PlanningButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlanningButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PlanningButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReserverButton, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(ReserverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(PlanningButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(null);
        jPanel2.setMaximumSize(new java.awt.Dimension(350, 550));
        jPanel2.setMinimumSize(new java.awt.Dimension(350, 550));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 550));

        NomLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        NomLabel.setText("jLabel1");

        PrenomLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        PrenomLabel.setText("jLabel1");

        DecoButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DecoButton.setText("Se deconnecter");
        DecoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecoButtonActionPerformed(evt);
            }
        });

        AgeLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        AgeLabel.setText("jLabel1");

        NationnaliteLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        NationnaliteLabel.setText("jLabel1");

        InfoLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        InfoLabel.setText("Info Joueur");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NationnaliteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PrenomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(InfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(DecoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(InfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(NomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PrenomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NationnaliteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(DecoButton)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DecoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecoButtonActionPerformed
        this.dispose();
        Connexion con = new Connexion();
        String[] nulité = new String[]{};
        con.main(nulité);
            // TODO add your handling code here:
    }//GEN-LAST:event_DecoButtonActionPerformed

    private void ReserverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReserverButtonActionPerformed
        this.dispose();
        PlayerTrain plt = new PlayerTrain(sauvegarde[0],sauvegarde[1],sauvegarde[2]);
        plt.openWindow();
        plt.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_ReserverButtonActionPerformed

    private void PlanningButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlanningButton1ActionPerformed
        this.dispose();
        PlanningJoueur  pnj = new PlanningJoueur();
        pnj.openWindow();
// TODO add your handling code here:
    }//GEN-LAST:event_PlanningButton1ActionPerformed

    /**
     * 
     * 
     */
    public static void openWindow(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JButton DecoButton;
    private javax.swing.JLabel InfoLabel;
    private javax.swing.JLabel NationnaliteLabel;
    private javax.swing.JLabel NomLabel;
    private javax.swing.JButton PlanningButton1;
    private javax.swing.JLabel PrenomLabel;
    private javax.swing.JButton ReserverButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
