/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ceif
 */
public class PlayerTrain extends javax.swing.JFrame {
    String horaire;
    public static String[] InfoNom;
    String driver ="com.mysql.cj.jdbc.Driver";
            String url = "jdbc:mysql://45.90.162.130:3306/admin_cpoaG4S3";
            String username = "admin_cpoa";
            String password = "5LzPRC86Gx";
    public Connection con;
    public String lidTerrain;
    public String JoueurId;
    String[] sauvegarde = new String[3];
    /**
     * Creates new form PlayerTrain
     */
    public PlayerTrain() {
        
    }
    public PlayerTrain(String Jid,String Nom , String Prénom) {
        sauvegarde[0]=Jid;
        sauvegarde[1]=Nom;
        sauvegarde[2]=Prénom;
        initComponents();
        System.out.println("marche 1");
        jComboBox1.removeAllItems();
        jComboBox1.addItem("10");
        jComboBox1.addItem("12");
        jComboBox1.addItem("14");
        jComboBox1.addItem("16");
        jComboBox1.addItem("18");
        JoueurId=Jid;
        System.out.println("marche 2");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ReserverButton = new javax.swing.JButton();
        RechargerButton = new javax.swing.JButton();
        ReservationLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(195, 68, 19));
        jPanel1.setBorder(null);

        jTable1.setForeground(new java.awt.Color(1, 1, 1));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null}
            },
            new String [] {
                "Terrain"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel1.setText("Terrain disponible :");

        jLabel2.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel2.setText("Reserver une scéance d'entrainement");

        jLabel3.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel3.setText("ma prochaine réservation :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(null);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("rechercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel4.setText("horaire :");

        ReserverButton.setText("reserver");
        ReserverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReserverButtonActionPerformed(evt);
            }
        });

        RechargerButton.setText("Recharger");
        RechargerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechargerButtonActionPerformed(evt);
            }
        });

        ReservationLabel.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        jButton2.setText("acceuil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(96, 96, 96))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(186, 186, 186))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(ReserverButton)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(RechargerButton))
                            .addComponent(ReservationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(115, 115, 115))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(330, 330, 330))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(RechargerButton))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addComponent(jLabel1)
                            .addGap(41, 41, 41)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ReserverButton)
                                .addComponent(jButton2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(ReservationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(103, 103, 103))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        maj();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    public void maj(){
        horaire= jComboBox1.getSelectedItem().toString();
        
        DefaultTableModel model = new DefaultTableModel(new String[]{"Terrain"}, 0);
        String d="";
           try{
            Class.forName(driver);
            con = DriverManager.getConnection(url,username,password);
            PreparedStatement listerTerrain = con.prepareStatement("select * from terrain where id not in ( select idTerrain from bTerrain where heure=?) ");
            listerTerrain.setString(1,horaire);
            ResultSet resultats = listerTerrain.executeQuery();
            while(resultats.next()){
                d = resultats.getString("nom");
                model.addRow(new Object[]{d});
            }
            
            jTable1.setModel(model);
            
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    
    private void ReserverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReserverButtonActionPerformed
        int column = 0;
        int row = jTable1.getSelectedRow();
        String rowvalue = jTable1.getModel().getValueAt(row, column).toString();
        System.out.println(rowvalue);
        
        try{
            Class.forName(driver);
            con = DriverManager.getConnection(url,username,password);
            
            PreparedStatement idTerrain = con.prepareStatement("select id from terrain where nom = ?");
            idTerrain.setString(1,rowvalue);
            ResultSet resultatsidTerrain = idTerrain.executeQuery();
            if(resultatsidTerrain.next()){
                lidTerrain = resultatsidTerrain.getString("id");
                System.out.println(lidTerrain);
            }
            PreparedStatement insererTableau = con.prepareStatement("INSERT INTO bTerrain(heure, idJoueur, idTerrain) "
                    + "VALUES (?,?,?)");
            insererTableau.setString(1,horaire);
            insererTableau.setString(2,JoueurId);
            insererTableau.setString(3,lidTerrain);
            int reussiounon = insererTableau.executeUpdate();
            
            if(reussiounon>0){
                JOptionPane.showMessageDialog(null, "Reservation réussie !", 
                "PopUp4", JOptionPane.CLOSED_OPTION);
                maj();
                resultatsidTerrain.close();
                insererTableau.close();
                idTerrain.close();
                con.close();
            }
            
            
        }catch(java.lang.ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "Vous n'avez pas choisis de terrain a reserver ...", 
                "PopUp4", JOptionPane.CLOSED_OPTION);
        }
        catch(Exception e){
            
            System.out.println(e.getMessage());
        }
// TODO add your handling code here:
    }//GEN-LAST:event_ReserverButtonActionPerformed

    private void RechargerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechargerButtonActionPerformed
        try{
            Class.forName(driver);
            con = DriverManager.getConnection(url,username,password);
            PreparedStatement listerReservation = con.prepareStatement("select * from bTerrain where idJoueur =? order by heure desc");
            listerReservation.setString(1,JoueurId);
            ResultSet resultats = listerReservation.executeQuery();
            
            
            PreparedStatement nomT = con.prepareStatement("select nom from terrain where id = ?");
            
            
            
            if(resultats.next()){
            nomT.setString(1,resultats.getString("idTerrain"));
            ResultSet resultatsNomT = nomT.executeQuery();
            if(resultatsNomT.next()){
                ReservationLabel.setText("Vous avez reserver le terrain " +resultatsNomT.getString("nom")+" à "+ resultats.getString("heure") +" heure");
                }
            resultatsNomT.close();
            resultats.close();
            listerReservation.close();
            nomT.close();
            con.close();
            };
            
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }// TODO add your handling code here:
    }//GEN-LAST:event_RechargerButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        PlayerHome plhm = new PlayerHome(sauvegarde[0],sauvegarde[1],sauvegarde[2]);
        plhm.openWindow();
        plhm.setVisible(true);
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * 
     */
    public static void openWindow() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerTrain().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RechargerButton;
    private javax.swing.JLabel ReservationLabel;
    private javax.swing.JButton ReserverButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
